/**
 * This class contains all the queries required by the program, written
 * for the Oracle database language.
 */

var queries = {
	// QA Related queries
	qa : {
		selectCategoryNames : 'SELECT "NAME" FROM "CGQA_COMPONENT_CATEGORIES" WHERE DEPRECATED_STATUS = 0',
		insertComponent : 'INSERT INTO "CGQA_COMPONENT_DETAILS"("COMPONENT_ID", "NAME", "STATUS", "DESCRIPTION",'
						+ ' "QUERY", "TYPE", "CATEGORY", "CREATED_BY", "SCHEDULE", "CREATION_DATETIME", "UPDATED_DATETIME") VALUES '
						+ '(COMPONENT_DETAILS_SEQ.nextval, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
		insertCategory : 'INSERT INTO "CGQA_COMPONENT_CATEGORIES"("CATEGORY_ID", "NAME") VALUES (COMPONENT_CATEGORIES_SEQ.nextval, ?)',
		insertComponentTables : 'INSERT INTO "CGQA_COMPONENT_TABLES"("TABLE_ID", "NAME", "COMPONENT") VALUES (COMPONENT_TABLES_SEQ.nextval, ?, ?)',
		selectComponentByName : 'SELECT * FROM "CGQA_COMPONENT_DETAILS" WHERE "NAME" = ? AND "DEPRECATED_STATUS" = 0',
		selectAllTablesByName : 'SELECT "TABLE_NAME" FROM "ALL_TABLES" WHERE "TABLE_NAME" = ?',
		selectComponentById : 'SELECT * FROM "CGQA_COMPONENT_DETAILS" WHERE "COMPONENT_ID" = ?',
		insertComponentHistory : 'INSERT INTO "CGQA_COMPONENT_DETAILS_HISTORY"("COMPONENT_HISTORY_ID", "COMPONENT", "NAME",'
								+ ' "STATUS", "DESCRIPTION", "QUERY", "TYPE", "CATEGORY", "CREATION_DATETIME", "CREATED_BY",'
								+ ' "SCHEDULE", "RUN_PRIORITY", "UPDATED_DATETIME", "UPDATED_BY") VALUES '
								+ '(COMPONENT_DETAILS_HISTORY_SEQ.nextval, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
		selectLatestCompHistoryDetailsById : 'SELECT "COMPONENT_HISTORY_ID" FROM "CGQA_COMPONENT_DETAILS_HISTORY" WHERE "COMPONENT" = ? '
										+ 'AND "UPDATED_DATETIME" = (SELECT MAX("UPDATED_DATETIME") FROM "CGQA_COMPONENT_DETAILS_HISTORY" WHERE "COMPONENT" = ?)',
		selectGroupsByComponent : 'SELECT "NAME", "ORDER_NUMBER" FROM "CGQA_COMPONENT_GROUPS" WHERE "COMPONENT" = ?',
		insertGroupsHistory : 'INSERT INTO "CGQA_COMPONENT_GROUPS_HISTORY"("GROUP_HISTORY_ID", "COMPONENT_HISTORY", "NAME", "ORDER_NUMBER") VALUES '
							+ '(COMPONENT_GROUPS_HISTORY_SEQ.nextval, ?, ?, ?)',
		selectCompTablesByComp : 'SELECT "NAME" FROM "CGQA_COMPONENT_TABLES" WHERE "COMPONENT" = ?',
		insertTablesHistory : 'INSERT INTO "CGQA_COMPONENT_TABLES_HISTORY"("TABLE_HISTORY_ID", "COMPONENT_HISTORY", "NAME") VALUES '
							+ '(COMPONENT_TABLES_HISTORY_SEQ.nextval, ?, ?)',
		deleteGroups : 'DELETE FROM "CGQA_COMPONENT_GROUPS" WHERE "COMPONENT" = ?',
		deleteTables : 'DELETE FROM "CGQA_COMPONENT_TABLES" WHERE "COMPONENT" = ?',
		updateComponent : 'UPDATE "CGQA_COMPONENT_DETAILS" SET "NAME" = ?, "DESCRIPTION" = ?, "QUERY" = ?, "TYPE" = ?, "CATEGORY" = ?, "UPDATED_BY" = ?, '
						+ '"UPDATED_DATETIME" = ? WHERE "COMPONENT_ID" = ?',
		selectCompForDisplay : 'SELECT D."COMPONENT_ID" "COMPONENT_ID", D."NAME" "NAME", D."DESCRIPTION" "DESCRIPTION", '
								+ 'D."QUERY" "QUERY", D."TYPE" "TYPE", D."CREATED_BY" "CREATED_BY", D."UPDATED_BY" "UPDATED_BY", C."NAME" "CATEGORY" '
								+ 'FROM "CGQA_COMPONENT_DETAILS" D INNER JOIN "CGQA_COMPONENT_CATEGORIES" C ON D."CATEGORY" = C."CATEGORY_ID" '
								+ 'WHERE D."DEPRECATED_STATUS" = 0 AND D."COMPONENT_ID" = ?',
		selectCategoryByName : 'SELECT * FROM "CGQA_COMPONENT_CATEGORIES" WHERE "NAME" = ? AND "DEPRECATED_STATUS" = 0',
		// Frank's Queries
		insertGroup : "INSERT INTO CGQA_COMPONENT_GROUPS (GROUP_ID,NAME,COMPONENT,ORDER_NUMBER) VALUES (CGQA_COMPONENT_GROUPS_SEQ.NEXTVAL, ?, ?, ?)",
		// Jeegna's Queries
		createTempTable : "CREATE TABLE table_name AS (?)",
		selectColumns : "SELECT * FROM table_name WHERE ROWNUM = 1",
		selectDistinctGroups : "SELECT DISTINCT \"column_name\" AS \"group\" FROM table_name ORDER BY \"column_name\"",
		dropTemporaryTable : "DROP TABLE table_name",
		lastNumberTableNameSequence : "SELECT COMPONENT_TEMP_TABLE_NAME_SEQ.nextval AS \"nextval\" FROM dual",
		// Jacob's Queries
		selectCategories:
			'SELECT "CATEGORY_ID", "NAME", "PARENT_CATEGORY", "DEPRECATED_STATUS" '
				+ 'FROM CGQA_COMPONENT_CATEGORIES '
				+ 'WHERE "DEPRECATED_STATUS" = 0',

		selectComponents:
			'SELECT * '
				+ 'FROM CGQA_COMPONENT_DETAILS '
				+ 'WHERE "DEPRECATED_STATUS" = 0',

		selectCategory:
			'SELECT "CATEGORY_ID", "NAME", "PARENT_CATEGORY", "DEPRECATED_STATUS" '
				+ 'FROM CGQA_COMPONENT_CATEGORIES '
				+ 'WHERE CATEGORY_ID = ? AND "DEPRECATED_STATUS" = 0',

		selectNewestCategory:
			'SELECT "CATEGORY_ID", "NAME", "PARENT_CATEGORY", "DEPRECATED_STATUS" '
				+ 'FROM CGQA_COMPONENT_CATEGORIES '
				+ 'WHERE "NAME" = ? AND "DEPRECATED_STATUS" = 0',

		selectComponent:
			'SELECT "COMPONENT_ID", "NAME", "STATUS", "DESCRIPTION", "QUERY", "TYPE", "SCHEDULE", "RUN_PRIORITY", '
				+ '"CATEGORY", "CREATION_DATETIME", "CREATED_BY", "SCHEDULE", "UPDATED_DATETIME", "UPDATED_BY", "DEPRECATED_STATUS" '
				+ 'FROM CGQA_COMPONENT_DETAILS '
				+ 'WHERE COMPONENT_ID = ? AND "DEPRECATED_STATUS" = 0',

		selectCategoryComponents:
			'SELECT "COMPONENT_ID", "NAME", "STATUS", "DESCRIPTION", "QUERY", "TYPE", "SCHEDULE", "RUN_PRIORITY", '
				+ '"CATEGORY", "CREATION_DATETIME", "CREATED_BY", "SCHEDULE", "UPDATED_DATETIME", "UPDATED_BY", "DEPRECATED_STATUS" '
				+ 'FROM CGQA_COMPONENT_DETAILS '
				+ 'WHERE CATEGORY = ? AND "DEPRECATED_STATUS" = 0',

		selectComponentsJoinCategory:
			'SELECT COMPONENT_ID, d.NAME AS "NAME", STATUS, "DESCRIPTION", "QUERY", "TYPE", SCHEDULE, RUN_PRIORITY, '
			+ 'd.DEPRECATED_STATUS AS "DEPRECATED_STATUS", c.DEPRECATED_STATUS AS "DP_CAT", "CATEGORY", CREATION_DATETIME, '
			+ 'CREATED_BY, UPDATED_DATETIME, UPDATED_BY, '
			+ 'c.CATEGORY_ID AS "CATEGORY_ID", c.NAME AS "CATEGORY_NAME", c.PARENT_CATEGORY AS "PARENT_CATEGORY" '
			+ 'FROM CGQA_COMPONENT_DETAILS d '
			+ 'RIGHT OUTER JOIN CGQA_COMPONENT_CATEGORIES c ON c.CATEGORY_ID = d.CATEGORY '
			+ 'WHERE d.DEPRECATED_STATUS = 0 AND c.DEPRECATED_STATUS = 0 '
			+ 'ORDER BY CATEGORY_ID',

		selectComponentJoinCategory:
			'SELECT COMPONENT_ID, d.NAME AS "NAME", STATUS, "DESCRIPTION", "QUERY", "TYPE", SCHEDULE, RUN_PRIORITY, '
			+ 'd.DEPRECATED_STATUS AS "DEPRECATED_STATUS", c.DEPRECATED_STATUS AS "DP_CAT", "CATEGORY", CREATION_DATETIME, '
			+ 'CREATED_BY, UPDATED_DATETIME, UPDATED_BY, '
			+ 'c.CATEGORY_ID AS "CATEGORY_ID", c.NAME AS "CATEGORY_NAME", c.PARENT_CATEGORY AS "PARENT_CATEGORY" '
			+ 'FROM CGQA_COMPONENT_DETAILS d '
			+ 'RIGHT OUTER JOIN CGQA_COMPONENT_CATEGORIES c ON c.CATEGORY_ID = d.CATEGORY '
			+ 'WHERE COMPONENT_ID= ? AND d.DEPRECATED_STATUS = 0 AND c.DEPRECATED_STATUS = 0 '
			+ 'ORDER BY CATEGORY_ID',

		setRemovedCategory:
			'UPDATE CGQA_COMPONENT_CATEGORIES '
				+ 'SET DEPRECATED_STATUS = 1 '
				+ 'WHERE CATEGORY_ID = ?',

		setRemovedComponent:
			'UPDATE CGQA_COMPONENT_DETAILS '
				+ 'SET DEPRECATED_STATUS = 1 '
				+ 'WHERE COMPONENT_ID = ?',
	}
}

module.exports = queries;